name: Deploy new version

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      bundle_version:
        description: 'Bundle verison'
        required: true

jobs:
  deploy:
    runs-on: macos-latest
  
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set environment variables from project settings
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          exec .github/scripts/set-env-from-xcodeproj.sh

      - name: Update iOS version Info.plist
        if: ${{ inputs.bundle_version }}
        uses: damienaicheh/update-ios-version-info-plist-action@v1.1.0
        with:
          info-plist-path: "./EMTools/Info.plist"
          bundle-short-version-string: "1.0"
          bundle-version: ${{ inputs.bundle_version }}
          print-file: true

      - name: Commit new version
        if: ${{ inputs.bundle_version }}
        run: git commit -am "Bump to ${{ inputs.bundle_version }}"

      - name: Push changes
        if: ${{ inputs.bundle_version }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Import signing certificate
        if: ${{ inputs.bundle_version }}
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh

      - name: Import provisioning profile
        if: ${{ inputs.bundle_version }}
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh

      - name: Build app
        if: ${{ inputs.bundle_version }}
        run: |
          fastlane run build_app

      - name: Upload build artifacts
        if: ${{ inputs.bundle_version }}
        uses: actions/upload-artifact@v2
        with:
          name: build.log
          path: ~/Library/Logs/gym/*.log

      - name: Upload app to App Store Connect
        if: ${{ inputs.bundle_version }}
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f "$PRODUCT_NAME.ipa" -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"
